import { describe, it, expect } from 'vitest'
import { getListenAllUrl, type Reading } from '../data/schedule'

function r(book: string, chapter: number, url: string): Reading {
  return { label: `${book} ${chapter}`, book, chapter, audioUrl: url }
}

describe('getListenAllUrl', () => {
  it('combines multiple readings into a single biblegateway url', () => {
    const torah = r('Exodus', 6, 'https://www.biblegateway.com/audio/purevoice/niv/Exod.6')
    const tanakh = r('Psalms', 66, 'https://www.biblegateway.com/audio/purevoice/niv/Ps.66')
    const nt = r('Luke', 22, 'https://www.biblegateway.com/audio/purevoice/niv/Luke.22')

    const url = getListenAllUrl({ torah, tanakh, nt })
    expect(url).toBe('https://www.biblegateway.com/audio/purevoice/niv/Exod.6,Ps.66,Luke.22')
  })

  it('handles missing tanakh reading', () => {
    const torah = r('Exodus', 6, 'https://www.biblegateway.com/audio/purevoice/niv/Exod.6')
    const nt = r('Luke', 22, 'https://www.biblegateway.com/audio/purevoice/niv/Luke.22')

    const url = getListenAllUrl({ torah, nt })
    expect(url).toBe('https://www.biblegateway.com/audio/purevoice/niv/Exod.6,Luke.22')
  })

  it('avoids duplicating chapters when audioUrl already contains multiple chapters', () => {
    // Simulate a reading where audioUrl is already multi-chapter (as generated by transform-csv.ts)
    const torah = { 
      label: "Leviticus 4:27-5:10", 
      book: "Leviticus", 
      chapter: 4, 
      audioUrl: "https://www.biblegateway.com/audio/purevoice/niv/Lev.4,Lev.5" 
    }
    const nt = {
      label: "Matthew 16:1-20",
      book: "Matthew",
      chapter: 16,
      audioUrl: "https://www.biblegateway.com/audio/purevoice/niv/Matt.16"
    }

    const url = getListenAllUrl({ torah, nt })
    // Should NOT be .../Lev.4,Lev.4,Lev.4,Lev.5...
    expect(url).toBe('https://www.biblegateway.com/audio/purevoice/niv/Lev.4,Lev.5,Matt.16')
  })
})
